name: Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Say Hello
      run: echo "Hello, World!"

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'test-app'
        tag: '1.0.0'
        path: 'src/'
        builder: 'gcr.io/paketo-buildpacks/builder:base'
        env: 'TEST=TEST'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-app:1.0.0'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'        
              
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: print deploy
      run: echo "test deploy"