name: Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Say Hello
      run: echo "Hello, World!"

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'test-app'
        tag: '${{github.sha}}'
        path: 'src/'
        builder: 'gcr.io/paketo-buildpacks/builder:base'
        env: 'TEST=TEST'

    - name: Scan Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'test-app:${{github.sha}}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'        

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1 

    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: 'test-app:${{github.sha}}'

    - name: publish artifact
      uses: anchore/sbom-action/publish-sbom@v0
      with:
        sbom-artifact-match: ".*\\.spdx$"                  

    - name: Deploy to AWS
      run: |
        # Your AWS CLI commands go here
        aws s3 ls          
              
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: print deploy
      run: echo "test deploy"