name: Hello World

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Say Hello
      run: echo "Hello, World!"

    - name: Build image
      uses: mamezou-tech/buildpacks-action@master
      with:
        image: 'test-app'
        tag: '1.0.0'
        path: 'src/'
        builder: 'gcr.io/paketo-buildpacks/builder:base'
        env: 'TEST=TEST'
              
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: print deploy
      run: echo "test deploy"